--- 
abstract: turn templates into static websites
author: 
  - Chisel Wright<chiselwright@users.berlios.de>
build_requires: 
  File::Find: 0
  File::Temp: 0.18
  Test::File::Contents: 0.05
  Test::More: 0.72
  Test::NoWarnings: 0.083
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Zucchini
no_index: 
  directory: 
    - legacy
    - inc
    - t
recommends: 
  Config::General: 2.37
requires: 
  Carp: 0
  Config::Any: 0.09
  Digest::MD5: 2.36
  File::Basename: 0
  File::Copy: 2.09
  File::Find: 0
  File::Rsync: 0.42
  File::Slurp: 9999.12
  File::Temp: 0
  File::stat: 1.00
  HTML::Lint: 2.02
  IO::File: 0
  Moose: 0.55
  Net::FTP: 2.77
  Path::Class: 0.16
  Template: 2.19
  version: 0
version: 0.0.11
