---
name: Zucchini
version: 0.0.3
author:
  - 'Chisel Wright<chiselwright@users.berlios.de>'
abstract: turn templates into static websites
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Class::Std: 0.0.8
  Config::Any: 0.08
  Digest::MD5: 2.36
  File::Basename: 0
  File::Copy: 2.09
  File::Find: 0
  File::Rsync: 0.42
  File::Slurp: 9999.12
  File::Temp: 0
  File::stat: 1.00
  IO::File: 0
  Net::FTP: 2.77
  Path::Class: 0.16
  Template: 2.19
  version: 0
build_requires:
  File::Find: 0
  File::Temp: 0.18
  Test::More: 0.72
recommends:
  Config::General: 2.37
no_index:
  directory:
    - legacy
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
